library(dplyr)
library(fields)
library(lubridate)
library(rjags)
library(R2jags)
library(tidyr)
library(vegan)
library(zoo)
library(parallel)

source('src/analyses.R')
source('src/misc.R')
source('src/prep.data.R')
source("src/Loading data.R")
